### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by LeqitFoxHDYT** [atomicnetworkseu/atomicradio-ts3abinterface#92]
Hi,

I have a problem with the interface.
When I run the command "ng build --prod --base-href=/" then comes the following error:

> Error: Error on worker #1: TypeError: ts.updateIdentifier is not a function
    at Object.generateSetClassMetadataCall (/home/Web/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/metadata.js:33:21)
    at InjectableDecoratorHandler.analyze (/home/Web/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/injectable.js:72:46)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (/home/Web/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:345:40)
    at analyze (/home/Web/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:297:58)
    at _loop_1 (/home/Web/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:319:21)
    at NgccTraitCompiler.TraitCompiler.analyzeClass (/home/Web/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:325:35)
    at NgccTraitCompiler.analyzeFile (/home/Web/node_modules/@angular/compiler-cli/ngcc/src/analysis/ngcc_trait_compiler.js:47:26)
    at DecorationAnalyzer.analyzeProgram (/home/Web/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:134:39)
    at Transformer.analyzeProgram (/home/Web/node_modules/@angular/compiler-cli/ngcc/src/packages/transformer.js:129:57)
    at Transformer.transform (/home/Web/node_modules/@angular/compiler-cli/ngcc/src/packages/transformer.js:75:27)
    at ClusterMaster.onWorkerMessage (/home/Web/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:194:27)
    at /home/Web/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:54:95
    at ClusterMaster.<anonymous> (/home/Web/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:292:57)
    at step (/home/Web/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/Web/node_modules/tslib/tslib.js:122:57)
    at /home/Web/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/Web/node_modules/tslib/tslib.js:111:16)
    at EventEmitter.<anonymous> (/home/Web/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:286:32)
    at EventEmitter.emit (events.js:375:28)
An unhandled exception occurred: NGCC failed.
See "/tmp/ng-5RIOHX/angular-errors.log" for further details.

Can you help me with this error?

Thanks in advance

**Comment by VocalZero** [comment]
We never had this error. Try npm install `typescript@">=3.0.0 <3.9.7"` maybe this will fix your problem.

**Comment by VocalZero** [comment]
If it still does not work please give me more information about your environment. Which OS you are using and version of Angular CLI, Node and NPM.

**Comment by LeqitFoxHDYT** [comment]
> We never had this error. Try `npm install typescript@">=3.0.0 <3.9.7"` and then `ng build --prod --base-href=/` maybe this will fix your problem.

Now this Error comes: 

> ERROR in ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: No argument named $ignore-warning.
  ┌──> node_modules/bootstrap/scss/_forms.scss
40│   @include form-control-focus($ignore-warning: true);
  │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ invocation
  ╵
  ┌──> src/assets/scss/core/mixins/_forms.scss
1 │ @mixin form-control-focus() {
  │        ━━━━━━━━━━━━━━━━━━━━ declaration
  ╵
  node_modules/bootstrap/scss/_forms.scss 40:3  form-control-focus()
  node_modules/bootstrap/scss/_forms.scss 40:3  @import
  src/assets/scss/argon.scss 35:9               @import
  /home/atomicradio-ts3abinterface/src/styles.scss 4:9                                     root stylesheet
    at /home/atomicradio-ts3abinterface/node_modules/webpack/lib/NormalModule.js:316:20
    at /home/atomicradio-ts3abinterface/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/atomicradio-ts3abinterface/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/atomicradio-ts3abinterface/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/atomicradio-ts3abinterface/node_modules/sass-loader/dist/index.js:73:7
    at Function.call$2 (/home/atomicradio-ts3abinterface/node_modules/sass/sass.dart.js:87203:16)
    at _render_closure1.call$2 (/home/atomicradio-ts3abinterface/node_modules/sass/sass.dart.js:76994:12)
    at _RootZone.runBinary$3$3 (/home/atomicradio-ts3abinterface/node_modules/sass/sass.dart.js:25521:18)
    at _RootZone.runBinary$3 (/home/atomicradio-ts3abinterface/node_modules/sass/sass.dart.js:25525:19)
    at _FutureListener.handleError$1 (/home/atomicradio-ts3abinterface/node_modules/sass/sass.dart.js:23975:19)
    at _Future__propagateToListeners_handleError.call$0 (/home/atomicradio-ts3abinterface/node_modules/sass/sass.dart.js:24271:40)
    at Object._Future__propagateToListeners (/home/atomicradio-ts3abinterface/node_modules/sass/sass.dart.js:3500:88)
    at _Future._completeError$2 (/home/atomicradio-ts3abinterface/node_modules/sass/sass.dart.js:24099:9)
    at _AsyncAwaitCompleter.completeError$2 (/home/atomicradio-ts3abinterface/node_modules/sass/sass.dart.js:23491:12)
    at Object._asyncRethrow (/home/atomicradio-ts3abinterface/node_modules/sass/sass.dart.js:3256:17)
    at /home/atomicradio-ts3abinterface/node_modules/sass/sass.dart.js:13326:20
 @ multi ./src/styles.scss styles[0]
ERROR in The Angular Compiler requires TypeScript >=3.6.4 and <3.9.0 but 3.9.6 was found instead.

**Comment by TwitchBluelow** [comment]
Same error here
OS: Windows 10 64bit
Node: 14.17.0
NPM: 6.14.13

**Comment by VocalZero** [comment]
Take a look at the latest commit and tell me if it works for you.

**Comment by TwitchBluelow** [comment]
Changed the commit to `6f8614be8486f4ffec4d1af2b665547f845beb6a` and it works perfectly. Still getting the Typescript mismatch error but installed it with `npm install typescript@">=3.0.0 <3.9.0"`

**Comment by VocalZero** [comment]
Perfect and thanks for the info. I will have a look at the Typescript problem soon.

**Comment by VocalZero** [comment]
@LeqitFoxHDYT Does the problem still exist? If not, I will close the issue soon.
